name: CD - Deploy to Mac Mini

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Mac Mini
        run: |
          cd ~/projects/umc-9th-springboot-sweetheart

          echo "📥 Pulling latest code..."
          git pull origin main

          echo "🐳 Rebuilding Docker containers..."
          docker compose down
          docker compose up --build -d

          echo "⏳ Waiting for services to start..."
          sleep 10

          echo "✅ Checking service health..."
          docker compose ps

          # Health check
          if curl -f http://localhost:8080/actuator/health; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed - health check failed"
            docker compose logs backend
            exit 1
          fi

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment to Mac Mini succeeded!"
          else
            echo "❌ Deployment to Mac Mini failed!"
          fi
